# Generated by Django 4.2 on 2026-01-21 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_bloka', models.CharField(max_length=50)),
                ('sadrzaj', models.JSONField()),
                ('redosled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stranica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('tagovi', models.TextField(blank=True, null=True)),
                ('datum_izmena', models.DateTimeField(auto_now=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Podsetnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vreme_slanja', models.DateTimeField()),
                ('status', models.CharField(default='aktivan', max_length=20)),
                ('blok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blok')),
            ],
        ),
        migrations.AddField(
            model_name='blok',
            name='stranica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stranica'),
        ),
    ]
