# Generated by Django 6.0.1 on 2026-02-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projekat_zavrsen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorija',
            options={'verbose_name': 'Kategorija', 'verbose_name_plural': 'Kategorije'},
        ),
        migrations.AlterModelOptions(
            name='komentar',
            options={'verbose_name': 'Komentar', 'verbose_name_plural': 'Komentari'},
        ),
        migrations.AlterModelOptions(
            name='projekat',
            options={'verbose_name': 'Projekat', 'verbose_name_plural': 'Projekti'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Korisnik', 'verbose_name_plural': 'Korisnici'},
        ),
        migrations.AlterModelOptions(
            name='zadatak',
            options={'verbose_name': 'Zadatak', 'verbose_name_plural': 'Zadaci'},
        ),
    ]
